export const SET_ANNOUNCEMENT_DATA = 'SET_ANNOUNCEMENT_DATA';
export const SET_ERROR_DATA = 'SET_ERROR_DATA';
export const DELETE_ANNOUNCEMENT_DATA = 'DELETE_ANNOUNCEMENT_DATA';
export const DELETE_ERROR_DATA = 'DELETE_ERROR_DATA';